spring:
  application:
    name: microloansStub
  datasource:
    url: jdbc:h2:file:C:/Users/VAgafonov/Java/myDB
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
management:
  server:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
logging:
  file:
    name: C:\\Users\\VAgafonov\\Java\\logs\\stub.log
    max-size: 50MB
  pattern:
    console: "%d{HH:mm:ss.SSS} %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
server:
  port: 8080
X: 1
